name: Unit test - Jest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: npm install
      run: npm install --include=dev
    - name: Run tests
      run: npm test -- --watchAll=false
